version: '3.9'
services:
  xui:
    image: enwaiax/x-ui
    container_name: x-ui
    volumes:
      - /db/:/etc/x-ui/
      - /root/cert/:/root/cert/
    restart: unless-stopped
    network_mode: host
